### PR TITLE
Fixed cases for inputs and outputs greater than 32 bits

### PR DESCRIPTION
**Pull request by austinliou**
Fixed incorrect outputs if input schema length exceeds 32 bits or if a field length exceeds 32 bits.

This is needed because when JS does bitwise operations, it [truncates operands to 32-bit sequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators) (wtf?), despite 'Number' supporting 52-bit integers (IEEE-754).

To get around this, I effectively split all input arguments and output values into two 32-bit registers (see split32() function) before performing bitwise operations.  Unfortunately, this means the code becomes a bit more complicated than described in your blog :(

As an example, the following schema should now work correctly:
[{ length: 8, name: 'location' },
{ length: 40, name: 'uid' },
{ length: 4, name: 'type' }]

There's no error checking, so this will still break if you exceed 52 bits!

### CODE REVIEW

**Comment by danprince** [comment]
Not ignoring this by the way. The solution looks good, but I've been busy and haven't quite decided whether the added code complexity is worth the feature. Might be preferable to just throw an error if the number is going to break.

I'd be interested to hear other people's opinions though, if anyone cares to comment here?

**Comment by austinliou** [comment]
No problem, I'm fully aware that this can probably be made more readable or efficient, but I haven't attempted either of those yet, or updated the tests to include new cases either.  In fact, there might even be a more elegant solution that I've missed entirely.

In the spirit of keeping this as a simple "tiny binary format", maybe you're right and it would be better to constrain to 32 bits, and instead branch this commit out separately.  Up to you!

**Comment by danprince** [comment]
Yeah. I think it's important that another dev can quickly look at the pack/unpack methods and understand them in <10s. They should be as transparent as possible, you want to know exactly what kind of performance impact it will have. It's definitely a shame not to have support for >32 bit numbers, but I think it's the right trade off.

Who knows, maybe there's a market for `slightly-bigger-binary-format`...?

**Comment by danprince** [comment]
If you want to aim this at a 64-bit-support branch, I'll merge it there.

**Comment by austinliou** [comment]
Can do.  Make a new branch and I'll create a new PR for it.

**Comment by danprince** [comment]
Meant to do this after commenting, just skipped my mind. The branch is there now at  `64-bit-support`.

**Pull request closed without merging**
